// Costa Rican name pools for the demo seed. Split into first names and
// surnames so the seed can mix them into far more unique people than a fixed
// list of full names would allow (ADR-0002: seeded identities are stable under
// faker.seed(42)). Seeded from the foundation's example roster (FundavidaData)
// and expanded with common Tico given names and apellidos so 100+ seeded
// people rarely collide. Values are Spanish proper nouns shown raw, never
// passed through t() — like Sede, Province, and University values.
export const CR_FIRST_NAMES = [
  // From the example roster
  'Nicole',
  'Andres',
  'David',
  'Josue',
  'Ernesto',
  'Sofia',
  'Tatiana',
  'Daniel',
  'Adriana',
  'Keylor',
  'Viviana',
  'Daniela',
  'Juan',
  'Mariana',
  'Vanessa',
  'Kevin',
  'Sebastian',
  'Julian',
  'Victor',
  'Ricardo',
  'Mauricio',
  'Jessica',
  'Isaac',
  'Elana',
  'Dereck',
  'Jose',
  'Lionel',
  'Fernanda',
  'Yuliana',
  'Carlos',
  // Expansion: common Costa Rican given names
  'Maria',
  'Ana',
  'Luis',
  'Laura',
  'Andrea',
  'Gabriela',
  'Diego',
  'Esteban',
  'Felipe',
  'Pablo',
  'Natalia',
  'Karla',
  'Melissa',
  'Valeria',
  'Rodrigo',
  'Bryan',
  'Emanuel',
  'Gloriana',
  'Maricruz',
  'Randall',
  'Greivin',
  'Stephanie',
  'Allan',
  'Roberto',
  'Catalina',
  'Joel',
  'Wendy',
  'Marco',
] as const

export const CR_LAST_NAMES = [
  // From the example roster
  'Hidalgo',
  'Hernandez',
  'Quesada',
  'Gonzales',
  'Campos',
  'Arguedas',
  'Madrigal',
  'Arroyo',
  'Solano',
  'Quiros',
  'Vargas',
  'Barboza',
  'Calderon',
  'Montero',
  'Jimenez',
  'Chavez',
  'Gutierrez',
  'Barrantes',
  'Barrientos',
  'Guzman',
  'Rojas',
  'Pacheco',
  'Ortiz',
  'Salazar',
  // Expansion: common Costa Rican apellidos
  'Mora',
  'Rodriguez',
  'Sanchez',
  'Ramirez',
  'Castro',
  'Cordero',
  'Alvarez',
  'Sandoval',
  'Chacon',
  'Brenes',
  'Mata',
  'Mena',
  'Soto',
  'Araya',
  'Villalobos',
  'Zuniga',
  'Murillo',
  'Fonseca',
  'Aguilar',
  'Bonilla',
  'Vega',
  'Navarro',
  'Esquivel',
  'Fallas',
  'Camacho',
  'Herrera',
  'Marin',
  'Porras',
  'Solis',
] as const
